# https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/constructor

branches:
  only:
    - master

environment:
  matrix:
    # these next two cover "current" conda
    - PYTHON_VERSION: "2.7"
      CONDA_CANARY: "true"
    - PYTHON_VERSION: "3.7"
      CONDA_CANARY: "true"
    # older, still-supported releases of conda
    - PYTHON_VERSION: "3.6"
      CONDA_VERSION: "4.6"

matrix:
  allow_failures:
    - PYTHON_VERSION: "3.7"
      CONDA_CANARY: "true"
    - PYTHON_VERSION: "2.7"
      CONDA_CANARY: "true"

platform:
  -x64

cache:
  - "C:\\condacache\\pkgs"

install:
  - appveyor DownloadFile https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-win-64.exe -FileName loner_conda.exe
  - set "CONDA_PKGS_DIRS=C:\condacache\pkgs"
  - set "CONDA_ALWAYS_YES=true"
  - set "CONDA_AUTO_UPDATE_CONDA=false"
  - if "%CONDA_CANARY%" == "" (
      loner_conda.exe create -q -p C:\test_conda python=%PYTHON_VERSION% conda=%CONDA_VERSION%
      ) else (
      loner_conda.exe create -q -p C:\test_conda -c conda-canary conda python=%PYTHON_VERSION%
      )
  # Install run dependencies
  - loner_conda.exe install -q -p C:\test_conda nsis pillow>=3.1 ruamel_yaml
  # Install test dependencies
  - loner_conda.exe install -q -p C:\test_conda pytest pytest-cov
  # so that the tests see the standalone conda that they need
  - mkdir C:\test_conda\standalone_conda
  - copy loner_conda.exe C:\test_conda\standalone_conda\conda.exe
  - call C:\test_conda\Scripts\activate
  # Install this package
  - python setup.py develop
  # Install conda canary before running tests, ensure conda is updated
  - conda info
  - conda init
  - call C:\test_conda\Scripts\activate
  - conda list

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - call C:\test_conda\Scripts\activate
  - pytest --cov=conda_bundle conda_bundle
  - python scripts\\run_examples.py
