package:
  name: conda-bundle
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only
  #    captures committed code, so pay attention.
  - git_url: ../

build:
  script:
    - pip install --no-deps -vv .
  entry_points:
    - conda-bundle=conda_bundle.main:main

requirements:
  host:
    - python
    - pip
  run:
    - conda >=4.6
    - python
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1      # [win]
    - nsis >=3.01       # [win]
    - jolevy::conda-pack >=0.5.0 # [unix]

# note: the forked conda-pack on my account has some patches to re-write binary paths in dependencies.
# it could be pursued to create archive-ready program distribution.
# I started that when conda-pack was stuck at 0.4.0 with no maintainer, but now they restarted the development with new people.
# It could be a good idea to check on what they did recently.

test:
  imports:
    - conda_bundle
  commands:
    - conda-bundle -V
    - conda-bundle --test .

about:
  home: https://conda.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Conda-bundle is a tool for constructing an installer for an app that should be
    distributed with its own conda environment.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/SED-Inria-Sophia/conda-bundle

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - kalefranz
    - msarahan
    - mingwandroid
    - nehaljwani
